import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from scripts import run_review


class InitCodexTests(unittest.TestCase):
    def test_init_codex_skips_when_agents_exists(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)
            agents_md = repo_dir / "AGENTS.md"
            agents_md.write_text("existing\n")

            with patch("scripts.run_review.subprocess.run") as mock_run:
                self.assertTrue(run_review.init_codex(repo_dir))
                mock_run.assert_not_called()

    def test_init_codex_writes_last_message_to_agents_md(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)

            def fake_run(cmd, **kwargs):
                self.assertIn("--output-last-message", cmd)
                output_path = Path(cmd[cmd.index("--output-last-message") + 1])
                output_path.write_text("# Project Overview\nGenerated by test.\n")
                return subprocess.CompletedProcess(cmd, 0, "", "")

            with patch("scripts.run_review.shutil.which", return_value="/usr/bin/codex"):
                with patch("scripts.run_review.subprocess.run", side_effect=fake_run) as mock_run:
                    self.assertTrue(run_review.init_codex(repo_dir))
                    self.assertTrue((repo_dir / "AGENTS.md").exists())
                    self.assertIn("Generated by test.", (repo_dir / "AGENTS.md").read_text())
                    self.assertEqual(mock_run.call_count, 1)


class CodexCommandTests(unittest.TestCase):
    def test_build_codex_review_command_uses_base_ref_and_repo_dir(self):
        repo_dir = Path("/tmp/repo")
        cmd = run_review.build_codex_command(
            repo_dir,
            review_mode=True,
            base_ref="origin/main"
        )

        self.assertEqual(cmd[:3], ["codex", "exec", "review"])
        self.assertIn("--base", cmd)
        self.assertIn("origin/main", cmd)
        self.assertIn("--full-auto", cmd)
        self.assertEqual(cmd[-3:], ["-C", str(repo_dir), "-"])

    def test_build_codex_command_can_bypass_sandbox(self):
        cmd = run_review.build_codex_command(
            Path("/tmp/repo"),
            bypass_sandbox=True
        )

        self.assertIn("--dangerously-bypass-approvals-and-sandbox", cmd)
        self.assertNotIn("--full-auto", cmd)


class ReviewPromptTests(unittest.TestCase):
    def test_generate_review_prompt_enforces_local_only_review(self):
        prompt = run_review.generate_review_prompt({
            "repo_dir": "workspace/repo",
            "base_ref": "origin/main",
            "head_ref": "HEAD",
            "owner": "openHiTLS",
            "repo": "openhitls",
            "pr_id": "1153",
            "changed_files": ["src/main.c"],
        })

        self.assertIn("Repository root: `workspace/repo`", prompt)
        self.assertIn("Review ONLY the local repository checkout", prompt)
        self.assertIn("Do NOT search the web.", prompt)
        self.assertIn("Do NOT open GitHub, GitLab, Gitee, or GitCode pages", prompt)


if __name__ == "__main__":
    unittest.main()
