import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from scripts import run_review


class InitCodexTests(unittest.TestCase):
    def test_init_codex_skips_when_agents_exists(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)
            agents_md = repo_dir / "AGENTS.md"
            agents_md.write_text("existing\n")

            with patch("scripts.run_review.subprocess.run") as mock_run:
                self.assertTrue(run_review.init_codex(repo_dir))
                mock_run.assert_not_called()

    def test_init_codex_writes_last_message_to_agents_md(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)

            def fake_run(cmd, **kwargs):
                self.assertIn("--output-last-message", cmd)
                output_path = Path(cmd[cmd.index("--output-last-message") + 1])
                output_path.write_text("# Project Overview\nGenerated by test.\n")
                return subprocess.CompletedProcess(cmd, 0, "", "")

            with patch("scripts.run_review.shutil.which", return_value="/usr/bin/codex"):
                with patch("scripts.run_review.subprocess.run", side_effect=fake_run) as mock_run:
                    self.assertTrue(run_review.init_codex(repo_dir))
                    self.assertTrue((repo_dir / "AGENTS.md").exists())
                    self.assertIn("Generated by test.", (repo_dir / "AGENTS.md").read_text())
                    self.assertEqual(mock_run.call_count, 1)


class CodexCommandTests(unittest.TestCase):
    def test_build_codex_command_bypasses_sandbox_by_default(self):
        cmd = run_review.build_codex_command(
            Path("/tmp/repo")
        )

        self.assertIn("--dangerously-bypass-approvals-and-sandbox", cmd)
        self.assertNotIn("--full-auto", cmd)
        self.assertEqual(cmd[-1], "-")

    def test_build_codex_command_can_use_sandbox(self):
        cmd = run_review.build_codex_command(
            Path("/tmp/repo"),
            use_sandbox=True
        )

        self.assertIn("--full-auto", cmd)
        self.assertNotIn("--dangerously-bypass-approvals-and-sandbox", cmd)
        self.assertEqual(cmd[-1], "-")


class ReviewPromptTests(unittest.TestCase):
    def test_generate_review_prompt_enforces_local_only_review(self):
        prompt = run_review.generate_review_prompt({
            "repo_dir": "workspace/repo",
            "base_ref": "origin/main",
            "head_ref": "HEAD",
            "owner": "openHiTLS",
            "repo": "openhitls",
            "pr_id": "1153",
            "changed_files": ["src/main.c"],
        })

        self.assertIn("Repository root: `workspace/repo`", prompt)
        self.assertIn("Review ONLY the local repository checkout", prompt)
        self.assertIn("Do NOT search the web.", prompt)
        self.assertIn("Do NOT open GitHub, GitLab, Gitee, or GitCode pages", prompt)

    def test_generate_review_prompt_mentions_assembly_review_rules(self):
        prompt = run_review.generate_review_prompt({
            "repo_dir": "workspace/repo",
            "base_ref": "origin/main",
            "head_ref": "HEAD",
            "owner": "openHiTLS",
            "repo": "openhitls",
            "pr_id": "1153",
            "changed_files": ["crypto/mldsa/src/asm/intt_armv8.S"],
        })

        self.assertIn("assembly files (`.S`, `.s`, `.asm`) as source code", prompt)
        self.assertIn("calling convention mismatches", prompt)


class FileCategorizationTests(unittest.TestCase):
    def test_categorize_files_treats_assembly_as_source(self):
        categories = run_review.categorize_files([
            "crypto/mldsa/src/asm/intt_armv8.S",
            "crypto/mldsa/src/asm/helper.s",
            "crypto/mldsa/src/asm/dispatch.asm",
            "docs/review-notes.md",
        ])

        self.assertEqual(
            categories["source"],
            [
                "crypto/mldsa/src/asm/intt_armv8.S",
                "crypto/mldsa/src/asm/helper.s",
                "crypto/mldsa/src/asm/dispatch.asm",
            ],
        )
        self.assertEqual(categories["docs"], ["docs/review-notes.md"])
        self.assertEqual(categories["other"], [])


if __name__ == "__main__":
    unittest.main()
