import json
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from scripts import run_review


class InitCodexTests(unittest.TestCase):
    def test_init_codex_skips_when_agents_exists(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)
            agents_md = repo_dir / "AGENTS.md"
            agents_md.write_text("existing\n")

            with patch("scripts.run_review.subprocess.run") as mock_run:
                self.assertTrue(run_review.init_codex(repo_dir))
                mock_run.assert_not_called()

    def test_init_codex_writes_last_message_to_agents_md(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)

            def fake_run(cmd, **kwargs):
                self.assertIn("--output-last-message", cmd)
                output_path = Path(cmd[cmd.index("--output-last-message") + 1])
                output_path.write_text("# Project Overview\nGenerated by test.\n")
                return subprocess.CompletedProcess(cmd, 0, "", "")

            with patch("scripts.run_review.shutil.which", return_value="/usr/bin/codex"):
                with patch("scripts.run_review.subprocess.run", side_effect=fake_run) as mock_run:
                    self.assertTrue(run_review.init_codex(repo_dir))
                    self.assertTrue((repo_dir / "AGENTS.md").exists())
                    self.assertIn("Generated by test.", (repo_dir / "AGENTS.md").read_text())
                    self.assertEqual(mock_run.call_count, 1)


class InitOpenCodeTests(unittest.TestCase):
    def test_init_opencode_skips_when_agents_exists(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)
            agents_md = repo_dir / "AGENTS.md"
            agents_md.write_text("existing\n")

            with patch("scripts.run_review.subprocess.run") as mock_run:
                self.assertTrue(run_review.init_opencode(repo_dir))
                mock_run.assert_not_called()

    def test_init_opencode_writes_stdout_to_agents_md(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)

            with patch("scripts.run_review.shutil.which", return_value="/usr/bin/opencode"):
                with patch(
                    "scripts.run_review.subprocess.run",
                    return_value=subprocess.CompletedProcess(
                        ["opencode", "run"],
                        0,
                        "# Project Overview\nGenerated by OpenCode.\n",
                        "",
                    ),
                ) as mock_run:
                    self.assertTrue(run_review.init_opencode(repo_dir))
                    self.assertTrue((repo_dir / "AGENTS.md").exists())
                    self.assertIn("Generated by OpenCode.", (repo_dir / "AGENTS.md").read_text())
                    self.assertEqual(mock_run.call_count, 1)

    def test_init_agents_md_falls_back_to_opencode(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir)

            with patch("scripts.run_review.init_codex", return_value=False) as mock_codex:
                with patch("scripts.run_review.init_opencode", return_value=True) as mock_opencode:
                    self.assertTrue(
                        run_review.init_agents_md(
                            repo_dir,
                            use_codex=True,
                            use_opencode=True,
                        )
                    )

        mock_codex.assert_called_once()
        mock_opencode.assert_called_once_with(repo_dir)


class CodexCommandTests(unittest.TestCase):
    def test_build_codex_command_bypasses_sandbox_by_default(self):
        cmd = run_review.build_codex_command(
            Path("/tmp/repo")
        )

        self.assertIn("-c", cmd)
        self.assertIn(
            f'model_reasoning_effort="{run_review.DEFAULT_CODEX_REASONING_EFFORT}"',
            cmd,
        )
        self.assertIn("--dangerously-bypass-approvals-and-sandbox", cmd)
        self.assertNotIn("--full-auto", cmd)
        self.assertEqual(cmd[-1], "-")

    def test_build_codex_command_can_use_sandbox(self):
        cmd = run_review.build_codex_command(
            Path("/tmp/repo"),
            use_sandbox=True
        )

        self.assertIn("--full-auto", cmd)
        self.assertNotIn("--dangerously-bypass-approvals-and-sandbox", cmd)
        self.assertEqual(cmd[-1], "-")

    def test_build_codex_command_can_set_model_and_reasoning_effort(self):
        cmd = run_review.build_codex_command(
            Path("/tmp/repo"),
            model=run_review.CODEX_SPARK_MODEL,
            reasoning_effort="xhigh",
        )

        self.assertIn("--model", cmd)
        self.assertIn(run_review.CODEX_SPARK_MODEL, cmd)
        self.assertIn("-c", cmd)
        self.assertIn('model_reasoning_effort="xhigh"', cmd)
        self.assertEqual(cmd[-1], "-")

    def test_build_claude_command_passes_prompt_as_argument(self):
        cmd = run_review.build_claude_command(
            "review this change",
            append_system_prompt="only issue blocks",
        )

        self.assertEqual(cmd[0:2], ["claude", "-p"])
        self.assertIn("--append-system-prompt", cmd)
        self.assertEqual(cmd[-1], "review this change")
        self.assertNotIn("-", cmd[2:])

    def test_build_gemini_command_uses_prompt_flag(self):
        cmd = run_review.build_gemini_command("review this change")

        self.assertEqual(cmd, ["gemini", "-p", "review this change", "-y"])

    def test_build_opencode_command_skips_permissions_by_default(self):
        cmd = run_review.build_opencode_command("review this change")

        self.assertEqual(cmd[0:2], ["opencode", "run"])
        self.assertIn("--dangerously-skip-permissions", cmd)
        self.assertEqual(cmd[-1], "review this change")

    def test_build_opencode_command_can_set_model(self):
        cmd = run_review.build_opencode_command(
            "review this change",
            model="anthropic/claude-sonnet-4",
        )

        self.assertIn("--model", cmd)
        self.assertIn("anthropic/claude-sonnet-4", cmd)


class ReviewPromptTests(unittest.TestCase):
    def test_generate_review_prompt_enforces_local_only_review(self):
        prompt = run_review.generate_review_prompt({
            "repo_dir": "workspace/repo",
            "base_ref": "origin/main",
            "head_ref": "HEAD",
            "owner": "openHiTLS",
            "repo": "openhitls",
            "pr_id": "1153",
            "changed_files": ["src/main.c"],
        })

        self.assertIn("Repository root: `workspace/repo`", prompt)
        self.assertIn("Review ONLY the local repository checkout", prompt)
        self.assertIn("Do NOT search the web.", prompt)
        self.assertIn("Do NOT compile, build, or run project test commands", prompt)
        self.assertIn("Do NOT open GitHub, GitLab, Gitee, or GitCode pages", prompt)

    def test_generate_review_prompt_mentions_assembly_review_rules(self):
        prompt = run_review.generate_review_prompt({
            "repo_dir": "workspace/repo",
            "base_ref": "origin/main",
            "head_ref": "HEAD",
            "owner": "openHiTLS",
            "repo": "openhitls",
            "pr_id": "1153",
            "changed_files": ["crypto/mldsa/src/asm/intt_armv8.S"],
        })

        self.assertIn("assembly files (`.S`, `.s`, `.asm`) as source code", prompt)
        self.assertIn("calling convention mismatches", prompt)


class FileCategorizationTests(unittest.TestCase):
    def test_categorize_files_treats_assembly_as_source(self):
        categories = run_review.categorize_files([
            "crypto/mldsa/src/asm/intt_armv8.S",
            "crypto/mldsa/src/asm/helper.s",
            "crypto/mldsa/src/asm/dispatch.asm",
            "docs/review-notes.md",
        ])

        self.assertEqual(
            categories["source"],
            [
                "crypto/mldsa/src/asm/intt_armv8.S",
                "crypto/mldsa/src/asm/helper.s",
                "crypto/mldsa/src/asm/dispatch.asm",
            ],
        )
        self.assertEqual(categories["docs"], ["docs/review-notes.md"])
        self.assertEqual(categories["other"], [])


class ParallelReviewReportTests(unittest.TestCase):
    def test_run_parallel_reviews_keeps_empty_report_when_output_is_unstructured(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir) / "repo"
            repo_dir.mkdir()
            output_dir = Path(tmpdir) / "out"
            output_dir.mkdir()
            context = {
                "repo_dir": str(repo_dir),
                "owner": "owner",
                "repo": "repo",
                "pr_id": "123",
                "changed_files": ["src/main.py"],
                "changed_files_count": 1,
            }

            def fake_gemini(repo_dir, prompt, output_file):
                output_file.write_text("No issues found.\n")
                return output_file, ["No issues found."]

            with patch("scripts.run_review.run_gemini_agent", side_effect=fake_gemini):
                review_reports, all_issues = run_review.run_parallel_reviews(
                    repo_dir=repo_dir,
                    context=context,
                    output_dir=output_dir,
                    use_claude=False,
                    use_gemini=True,
                    use_codex=False,
                )

            self.assertEqual(all_issues["gemini"], [])
            self.assertEqual(review_reports["gemini"], output_dir / "gemini_review.md")
            self.assertTrue((output_dir / "gemini_review.md").exists())
            self.assertTrue((output_dir / "gemini_review.html").exists())
            self.assertTrue((output_dir / "gemini_review.json").exists())
            self.assertIn(
                "No structured issues were parsed from the reviewer output.",
                (output_dir / "gemini_review.md").read_text(),
            )

    def test_run_parallel_reviews_defaults_codex_reasoning_effort_to_xhigh(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir) / "repo"
            repo_dir.mkdir()
            output_dir = Path(tmpdir) / "out"
            output_dir.mkdir()
            context = {
                "repo_dir": str(repo_dir),
                "owner": "owner",
                "repo": "repo",
                "pr_id": "123",
                "changed_files": ["src/main.py"],
                "changed_files_count": 1,
            }

            def fake_codex(repo_dir, prompt, output_file, **kwargs):
                self.assertEqual(kwargs["reasoning_effort"], "xhigh")
                output_file.write_text("")
                return output_file, []

            with patch("scripts.run_review.run_codex_review_agent", side_effect=fake_codex):
                run_review.run_parallel_reviews(
                    repo_dir=repo_dir,
                    context=context,
                    output_dir=output_dir,
                    use_claude=False,
                    use_gemini=False,
                    use_codex=True,
                )

    def test_run_parallel_reviews_can_run_opencode(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir) / "repo"
            repo_dir.mkdir()
            output_dir = Path(tmpdir) / "out"
            output_dir.mkdir()
            context = {
                "repo_dir": str(repo_dir),
                "owner": "owner",
                "repo": "repo",
                "pr_id": "123",
                "changed_files": ["src/main.py"],
                "changed_files_count": 1,
            }

            issue_block = "\n".join(
                [
                    "===ISSUE===",
                    "FILE: src/main.py",
                    "LINE: 7",
                    "SEVERITY: medium",
                    "TITLE: Example issue",
                    "PROBLEM: Example problem.",
                    "CODE:",
                    "```",
                    "bad()",
                    "```",
                    "FIX:",
                    "```",
                    "good()",
                    "```",
                    "===END===",
                ]
            )

            def fake_opencode(repo_dir, prompt, output_file, **kwargs):
                output_file.write_text(issue_block)
                return output_file, issue_block.splitlines()

            with patch("scripts.run_review.run_opencode_agent", side_effect=fake_opencode):
                review_reports, all_issues = run_review.run_parallel_reviews(
                    repo_dir=repo_dir,
                    context=context,
                    output_dir=output_dir,
                    use_claude=False,
                    use_gemini=False,
                    use_codex=False,
                    use_opencode=True,
                )

            self.assertEqual(review_reports["opencode"], output_dir / "opencode_review.md")
            self.assertEqual(len(all_issues["opencode"]), 1)
            self.assertEqual(all_issues["opencode"][0]["title"], "Example issue")


class ConsolidationTests(unittest.TestCase):
    def test_run_consolidation_defaults_to_codex_spark_with_xhigh_reasoning_effort(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir) / "repo"
            repo_dir.mkdir()
            output_dir = Path(tmpdir) / "out"
            output_dir.mkdir()
            review_report = output_dir / "gemini_review.md"
            review_report.write_text("===ISSUE===\nFILE: src/main.py\nLINE: 1\nTITLE: t\n===END===\n")

            with patch("scripts.run_review.run_codex_agent", return_value=(output_dir / "consolidation_output.txt", [])) as mock_codex:
                run_review.run_consolidation(
                    repo_dir=repo_dir,
                    review_reports={"gemini": review_report},
                    context={"owner": "owner", "repo": "repo", "pr_id": "123"},
                    output_dir=output_dir,
                )

        kwargs = mock_codex.call_args.kwargs
        self.assertEqual(kwargs["model"], run_review.CODEX_SPARK_MODEL)
        self.assertEqual(
            kwargs["reasoning_effort"],
            run_review.DEFAULT_CODEX_REASONING_EFFORT,
        )

    def test_run_consolidation_supports_opencode(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            repo_dir = Path(tmpdir) / "repo"
            repo_dir.mkdir()
            output_dir = Path(tmpdir) / "out"
            output_dir.mkdir()
            review_report = output_dir / "codex_review.md"
            review_report.write_text("===ISSUE===\nFILE: src/main.py\nLINE: 1\nTITLE: t\n===END===\n")

            with patch(
                "scripts.run_review.run_opencode_agent",
                return_value=(output_dir / "consolidation_output.txt", []),
            ) as mock_opencode:
                run_review.run_consolidation(
                    repo_dir=repo_dir,
                    review_reports={"codex": review_report},
                    context={"owner": "owner", "repo": "repo", "pr_id": "123"},
                    output_dir=output_dir,
                    consolidation_model="opencode",
                )

        mock_opencode.assert_called_once()


class MainDefaultsTests(unittest.TestCase):
    def test_main_defaults_to_codex_spark_consolidation_and_xhigh_effort(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            repo_dir = tmpdir_path / "repo"
            repo_dir.mkdir()
            output_dir = tmpdir_path / "out"
            context_path = tmpdir_path / "review_context.json"
            context_path.write_text(json.dumps({
                "repo_dir": str(repo_dir),
                "owner": "owner",
                "repo": "repo",
                "pr_id": "123",
                "changed_files": ["src/main.py"],
                "changed_files_count": 1,
            }))

            consolidated_issue = {
                "file": "src/main.py",
                "line": "1",
                "severity": "low",
                "confidence": "likely",
                "title": "t",
                "summary": "s",
                "reviewers": "codex, gemini",
            }

            def fake_run_consolidation(*args, **kwargs):
                consolidation_output = args[3] / "consolidation_output.txt"
                consolidation_output.write_text("===ISSUE===\nFILE: src/main.py\nLINE: 1\nTITLE: t\n===END===\n")
                return consolidation_output

            with patch.object(
                run_review.sys,
                "argv",
                [
                    "run_review.py",
                    "--context",
                    str(context_path),
                    "--gemini",
                    "--output",
                    str(output_dir),
                ],
            ):
                with patch(
                    "scripts.run_review.run_parallel_reviews",
                    return_value=(
                        {
                            "codex": output_dir / "codex_review.md",
                            "gemini": output_dir / "gemini_review.md",
                        },
                        {"codex": [], "gemini": []},
                    ),
                ):
                    with patch(
                        "scripts.run_review.run_consolidation",
                        side_effect=fake_run_consolidation,
                    ) as mock_consolidation:
                        with patch(
                            "scripts.run_review.parse_consolidated_issues",
                            return_value=[consolidated_issue],
                        ):
                            with patch(
                                "scripts.run_review.generate_final_report",
                                return_value=(
                                    output_dir / "final_report.md",
                                    output_dir / "final_report.html",
                                    output_dir / "final_report.json",
                                ),
                            ):
                                run_review.main()

        self.assertEqual(
            mock_consolidation.call_args.args[4],
            run_review.DEFAULT_CONSOLIDATION_MODEL,
        )
        self.assertEqual(
            mock_consolidation.call_args.kwargs["codex_reasoning_effort"],
            run_review.DEFAULT_CODEX_REASONING_EFFORT,
        )

    def test_main_wires_opencode_flag_into_review_pipeline(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            repo_dir = tmpdir_path / "repo"
            repo_dir.mkdir()
            output_dir = tmpdir_path / "out"
            context_path = tmpdir_path / "review_context.json"
            context_path.write_text(json.dumps({
                "repo_dir": str(repo_dir),
                "owner": "owner",
                "repo": "repo",
                "pr_id": "123",
                "changed_files": ["src/main.py"],
                "changed_files_count": 1,
            }))

            with patch.object(
                run_review.sys,
                "argv",
                [
                    "run_review.py",
                    "--context",
                    str(context_path),
                    "--no-codex",
                    "--opencode",
                    "--output",
                    str(output_dir),
                ],
            ):
                with patch(
                    "scripts.run_review.run_parallel_reviews",
                    return_value=(
                        {"opencode": output_dir / "opencode_review.md"},
                        {"opencode": []},
                    ),
                ) as mock_parallel:
                    with patch(
                        "scripts.run_review.generate_final_report",
                        return_value=(
                            output_dir / "final_report.md",
                            output_dir / "final_report.html",
                            output_dir / "final_report.json",
                        ),
                    ):
                        run_review.main()

        self.assertTrue(mock_parallel.call_args.kwargs["use_opencode"])
        self.assertFalse(mock_parallel.call_args.kwargs["use_codex"])


if __name__ == "__main__":
    unittest.main()
